# Generated by Django 5.2 on 2025-05-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('medium', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=22)),
                ('style', models.CharField(choices=[('Abstract', 'Abstract'), ('Abstract Expressionism', 'Abstract Expressionism'), ('Fine Art', 'Fine Art'), ('Expressionism', 'Expressionism'), ('Figurative', 'Figurative'), ('Modern', 'Modern')], max_length=30)),
                ('images', models.ImageField(upload_to='p_images/')),
                ('is_bestseller', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='p_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
        ),
    ]
