# Generated by Django 5.2 on 2025-04-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=250)),
                ('portfolio_image', models.ImageField(blank=True, upload_to='images/')),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('drawing', 'drawing'), ('sculpture', 'sculpture'), ('photography', 'photography'), ('print', 'print')], max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=20)),
                ('shipping_lane1', models.CharField(max_length=25)),
                ('shipping_lane2', models.CharField(max_length=25)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_state', models.CharField(max_length=25)),
                ('shipping_country', models.CharField(max_length=25)),
                ('billing_lane1', models.CharField(blank=True, max_length=25, null=True)),
                ('billing_lane2', models.CharField(blank=True, max_length=25, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_state', models.CharField(max_length=25)),
                ('billing_country', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('material', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(max_length=30)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=22)),
                ('style', models.CharField(choices=[('Abstract', 'Abstract'), ('Abstract Expressionism', 'Abstract Expressionism'), ('Fine Art', 'Fine Art'), ('Expressionism', 'Expressionism'), ('Figurative', 'Figurative'), ('Modern', 'Modern')], max_length=22)),
                ('images', models.ImageField(upload_to='p_images/')),
                ('is_bestseller', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='p_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
