# Generated by Django 5.1.4 on 2025-05-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=20)),
                ('shipping_lane1', models.CharField(max_length=25)),
                ('shipping_lane2', models.CharField(max_length=25)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_state', models.CharField(max_length=25)),
                ('shipping_country', models.CharField(max_length=25)),
                ('billing_lane1', models.CharField(blank=True, max_length=25)),
                ('billing_lane2', models.CharField(blank=True, max_length=25, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=25, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('portfolio_image', models.ImageField(blank=True, upload_to='images/')),
                ('photo', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('PAINTING', 'Painting'), ('DRAWING', 'drawing'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('PRINT', 'print')], max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
