# Generated by Django 5.2 on 2025-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
